DROP TABLE IF EXISTS devices;
DROP TABLE IF EXISTS posts;


CREATE TABLE devices (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    device TEXT NOT NULL
);

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    command TEXT NOT NULL,
    device INTEGER NOT NULL,
    FOREIGN KEY(device) REFERENCES devices(id)
);


